//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccessEmp
    {
        public int AccessID { get; set; }
        public Nullable<int> ReaderID { get; set; }
        public Nullable<int> EmpID { get; set; }
        public Nullable<bool> Permission { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<bool> Processed { get; set; }
    }
}
