//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AttMnData
    {
        public string Period { get; set; }
        public string EmpMonth { get; set; }
        public Nullable<int> EmpID { get; set; }
        public string EmpNo { get; set; }
        public string EmpName { get; set; }
        public string D1 { get; set; }
        public string D2 { get; set; }
        public string D3 { get; set; }
        public string D4 { get; set; }
        public string D5 { get; set; }
        public string D6 { get; set; }
        public string D7 { get; set; }
        public string D8 { get; set; }
        public string D9 { get; set; }
        public string D10 { get; set; }
        public string D11 { get; set; }
        public string D12 { get; set; }
        public string D13 { get; set; }
        public string D14 { get; set; }
        public string D15 { get; set; }
        public string D16 { get; set; }
        public string D17 { get; set; }
        public string D18 { get; set; }
        public string D19 { get; set; }
        public string D20 { get; set; }
        public string D21 { get; set; }
        public string D22 { get; set; }
        public string D23 { get; set; }
        public string D24 { get; set; }
        public string D25 { get; set; }
        public string D26 { get; set; }
        public string D27 { get; set; }
        public string D28 { get; set; }
        public string D29 { get; set; }
        public string D30 { get; set; }
        public string D31 { get; set; }
        public Nullable<byte> TotalDays { get; set; }
        public Nullable<double> WorkDays { get; set; }
        public Nullable<double> PreDays { get; set; }
        public Nullable<double> AbDays { get; set; }
        public Nullable<byte> RestDays { get; set; }
        public Nullable<byte> GZDays { get; set; }
        public Nullable<byte> LeaveDays { get; set; }
        public Nullable<double> HalfLeavesDay { get; set; }
        public Nullable<byte> OfficialDutyDays { get; set; }
        public Nullable<short> TEarlyIn { get; set; }
        public Nullable<short> TEarlyOut { get; set; }
        public Nullable<short> TLateIn { get; set; }
        public Nullable<short> TLateOut { get; set; }
        public Nullable<short> TWorkTime { get; set; }
        public Nullable<short> TNOT { get; set; }
        public Nullable<short> TGZOT { get; set; }
        public Nullable<short> ExpectedWrkTime { get; set; }
        public Nullable<short> OT1 { get; set; }
        public Nullable<short> OT2 { get; set; }
        public Nullable<short> OT3 { get; set; }
        public Nullable<short> OT4 { get; set; }
        public Nullable<short> OT5 { get; set; }
        public Nullable<short> OT6 { get; set; }
        public Nullable<short> OT7 { get; set; }
        public Nullable<short> OT8 { get; set; }
        public Nullable<short> OT9 { get; set; }
        public Nullable<short> OT10 { get; set; }
        public Nullable<short> OT11 { get; set; }
        public Nullable<short> OT12 { get; set; }
        public Nullable<short> OT13 { get; set; }
        public Nullable<short> OT14 { get; set; }
        public Nullable<short> OT15 { get; set; }
        public Nullable<short> OT16 { get; set; }
        public Nullable<short> OT17 { get; set; }
        public Nullable<short> OT18 { get; set; }
        public Nullable<short> OT19 { get; set; }
        public Nullable<short> OT20 { get; set; }
        public Nullable<short> OT21 { get; set; }
        public Nullable<short> OT22 { get; set; }
        public Nullable<short> OT23 { get; set; }
        public Nullable<short> OT24 { get; set; }
        public Nullable<short> OT25 { get; set; }
        public Nullable<short> OT26 { get; set; }
        public Nullable<short> OT27 { get; set; }
        public Nullable<short> OT28 { get; set; }
        public Nullable<short> OT29 { get; set; }
        public Nullable<short> OT30 { get; set; }
        public Nullable<short> OT31 { get; set; }
        public string L1 { get; set; }
        public string L2 { get; set; }
        public string L3 { get; set; }
        public string L4 { get; set; }
        public string L5 { get; set; }
        public string L6 { get; set; }
        public string L7 { get; set; }
        public string L8 { get; set; }
        public string L9 { get; set; }
        public string L10 { get; set; }
        public string L11 { get; set; }
        public string L12 { get; set; }
        public string L13 { get; set; }
        public string L14 { get; set; }
        public string L15 { get; set; }
        public string L16 { get; set; }
        public string L17 { get; set; }
        public string L18 { get; set; }
        public string L19 { get; set; }
        public string L20 { get; set; }
        public string L21 { get; set; }
        public string L22 { get; set; }
        public string L23 { get; set; }
        public string L24 { get; set; }
        public string L25 { get; set; }
        public string L26 { get; set; }
        public string L27 { get; set; }
        public string L28 { get; set; }
        public string L29 { get; set; }
        public string L30 { get; set; }
        public string L31 { get; set; }
    }
}
