//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Department
    {
        public Department()
        {
            this.Sections = new HashSet<Section>();
        }
    
        public short DeptID { get; set; }
        public string DeptName { get; set; }
    
        public virtual ICollection<Section> Sections { get; set; }
    }
}
