//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmpView
    {
        public string DeptName { get; set; }
        public string SectionName { get; set; }
        public string DesignationName { get; set; }
        public int EmpID { get; set; }
        public string EmpNo { get; set; }
        public string EmpName { get; set; }
        public Nullable<int> DesigID { get; set; }
        public Nullable<byte> ShiftID { get; set; }
        public Nullable<short> LocID { get; set; }
        public Nullable<byte> TypeID { get; set; }
        public Nullable<short> SecID { get; set; }
        public string CardNo { get; set; }
        public string NicNo { get; set; }
        public string FatherName { get; set; }
        public string BloodGroup { get; set; }
        public Nullable<System.DateTime> JoinDate { get; set; }
        public Nullable<System.DateTime> BirthDate { get; set; }
        public Nullable<System.DateTime> ValidDate { get; set; }
        public Nullable<System.DateTime> IssueDate { get; set; }
        public Nullable<System.DateTime> ResignDate { get; set; }
        public Nullable<bool> Status { get; set; }
        public string TypeName { get; set; }
        public string LocName { get; set; }
        public string ShiftName { get; set; }
        public short DeptID { get; set; }
    }
}
