//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class JobCardDetail
    {
        public string EmpDate { get; set; }
        public long JCDetailID { get; set; }
        public Nullable<int> EmpID { get; set; }
        public Nullable<System.DateTime> Dated { get; set; }
        public Nullable<short> WrkCardID { get; set; }
        public string Remarks { get; set; }
        public Nullable<int> JCAppID { get; set; }
    
        public virtual Emp Emp { get; set; }
        public virtual JobCardApp JobCardApp { get; set; }
    }
}
