//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LicenseInfo
    {
        public byte ID { get; set; }
        public string InvoiceNo { get; set; }
        public string CustomerName { get; set; }
        public string LicenseType { get; set; }
        public string DeviceType { get; set; }
        public string ClientMAC { get; set; }
        public string NoOfEmps { get; set; }
        public string NoOfUsers { get; set; }
        public string NoOfDevices { get; set; }
        public string ValidLicense { get; set; }
    }
}
