//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LvApplication
    {
        public LvApplication()
        {
            this.LvDatas = new HashSet<LvData>();
        }
    
        public int LvID { get; set; }
        public System.DateTime LvDate { get; set; }
        public string LvType { get; set; }
        public int EmpID { get; set; }
        public System.DateTime FromDate { get; set; }
        public System.DateTime ToDate { get; set; }
        public float NoOfDays { get; set; }
        public Nullable<bool> IsHalf { get; set; }
        public Nullable<bool> FirstHalf { get; set; }
        public Nullable<bool> HalfAbsent { get; set; }
        public string LvReason { get; set; }
        public string LvAddress { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<int> ApprovedBy { get; set; }
        public string LvStatus { get; set; }
        public Nullable<bool> Active { get; set; }
    
        public virtual Emp Emp { get; set; }
        public virtual User User { get; set; }
        public virtual LvType LvType1 { get; set; }
        public virtual ICollection<LvData> LvDatas { get; set; }
    }
}
