//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LvData
    {
        public string EmpDate { get; set; }
        public Nullable<int> LvID { get; set; }
        public int EmpID { get; set; }
        public System.DateTime AttDate { get; set; }
        public string LvCode { get; set; }
        public byte LvStatus { get; set; }
        public string Remarks { get; set; }
        public Nullable<bool> Processed { get; set; }
        public Nullable<bool> HalfLeave { get; set; }
        public Nullable<bool> FirstHalf { get; set; }
        public Nullable<bool> Active { get; set; }
    
        public virtual LvApplication LvApplication { get; set; }
        public virtual LvType LvType { get; set; }
    }
}
