//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LvQuota
    {
        public int EmpID { get; set; }
        public Nullable<double> A { get; set; }
        public Nullable<double> TA { get; set; }
        public Nullable<double> B { get; set; }
        public Nullable<double> TB { get; set; }
        public Nullable<double> C { get; set; }
        public Nullable<double> TC { get; set; }
    }
}
