//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Option
    {
        public short ID { get; set; }
        public string CompanyName { get; set; }
        public byte[] CompanyLogo { get; set; }
        public Nullable<System.DateTime> MonthlyStart { get; set; }
        public Nullable<System.DateTime> MonthlyEnd { get; set; }
    }
}
