//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReaderType
    {
        public ReaderType()
        {
            this.Readers = new HashSet<Reader>();
        }
    
        public byte RdrTypeID { get; set; }
        public string RdrTypeName { get; set; }
        public Nullable<byte> VendorID { get; set; }
    
        public virtual ICollection<Reader> Readers { get; set; }
    }
}
