//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViewSLData
    {
        public string DesignationName { get; set; }
        public string GradeName { get; set; }
        public string CompName { get; set; }
        public string JobTitle { get; set; }
        public string CityName { get; set; }
        public string RegionName { get; set; }
        public string LocName { get; set; }
        public string CrewName { get; set; }
        public string TypeName { get; set; }
        public string CatName { get; set; }
        public string ShiftName { get; set; }
        public string EmpNo { get; set; }
        public string EmpName { get; set; }
        public string CardNo { get; set; }
        public Nullable<bool> Status { get; set; }
        public string DeptName { get; set; }
        public string DivisionName { get; set; }
        public string SectionName { get; set; }
        public int SlID { get; set; }
        public int EmpID { get; set; }
        public Nullable<System.DateTime> DutyDate { get; set; }
        public string EmpDate { get; set; }
        public Nullable<System.TimeSpan> SHour { get; set; }
        public Nullable<System.TimeSpan> EHour { get; set; }
        public Nullable<System.TimeSpan> THour { get; set; }
        public string Remarks { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<int> ApprovedBy { get; set; }
        public Nullable<bool> Expr1 { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<short> CompanyID { get; set; }
        public Nullable<byte> TypeID { get; set; }
        public Nullable<short> CatID { get; set; }
        public Nullable<short> CrewID { get; set; }
        public short DivID { get; set; }
        public Nullable<short> LocID { get; set; }
        public Nullable<short> GradeID { get; set; }
        public short DeptID { get; set; }
        public Nullable<byte> ShiftID { get; set; }
        public Nullable<short> SecID { get; set; }
    }
}
