//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViewLeave
    {
        public string EmpNo { get; set; }
        public Nullable<int> EmpID { get; set; }
        public string EmpName { get; set; }
        public string JobTitle { get; set; }
        public string CatName { get; set; }
        public string TypeName { get; set; }
        public string SiteName { get; set; }
        public string CityName { get; set; }
        public string RegionName { get; set; }
        public string LocName { get; set; }
        public string DesignationName { get; set; }
        public string ShiftName { get; set; }
        public string SectionName { get; set; }
        public string CrewName { get; set; }
        public Nullable<int> FpID { get; set; }
        public string PinCode { get; set; }
        public string NicNo { get; set; }
        public string CardNo { get; set; }
        public Nullable<bool> Status { get; set; }
        public Nullable<System.DateTime> JoinDate { get; set; }
        public Nullable<byte> Gender { get; set; }
        public string DeptName { get; set; }
        public string CompName { get; set; }
        public string GradeName { get; set; }
        public string EmpDate { get; set; }
        public Nullable<System.DateTime> AttDate { get; set; }
        public Nullable<System.TimeSpan> DutyTime { get; set; }
        public string DutyCode { get; set; }
        public Nullable<bool> StatusLeave { get; set; }
        public string Remarks { get; set; }
        public string DivisionName { get; set; }
        public Nullable<short> CompanyID { get; set; }
        public Nullable<byte> TypeID { get; set; }
        public Nullable<short> CatID { get; set; }
        public Nullable<short> DivisionID { get; set; }
        public Nullable<byte> ShiftID { get; set; }
        public Nullable<short> DeptID { get; set; }
        public Nullable<short> SectionID { get; set; }
        public Nullable<short> CrewID { get; set; }
        public Nullable<byte> GradeID { get; set; }
        public Nullable<int> DesignationID { get; set; }
        public Nullable<short> LocID { get; set; }
    }
}
