//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViewJobCardTime
    {
        public string DesignationName { get; set; }
        public string GradeName { get; set; }
        public string CityName { get; set; }
        public string LocName { get; set; }
        public string CrewName { get; set; }
        public string TypeName { get; set; }
        public string CatName { get; set; }
        public string ShiftName { get; set; }
        public string EmpNo { get; set; }
        public string EmpName { get; set; }
        public Nullable<int> DesigID { get; set; }
        public Nullable<byte> Gender { get; set; }
        public Nullable<int> FpID { get; set; }
        public Nullable<System.DateTime> JoinDate { get; set; }
        public Nullable<bool> Status { get; set; }
        public string SectionName { get; set; }
        public string DeptName { get; set; }
        public string DivisionName { get; set; }
        public Nullable<short> CatID { get; set; }
        public Nullable<short> SecID { get; set; }
        public Nullable<byte> ShiftID { get; set; }
        public Nullable<byte> TypeID { get; set; }
        public Nullable<short> LocID { get; set; }
        public Nullable<short> GradeID { get; set; }
        public Nullable<short> DeptID { get; set; }
        public Nullable<short> DivID { get; set; }
        public Nullable<short> CrewID { get; set; }
        public Nullable<short> CityID { get; set; }
        public Nullable<int> EmpID { get; set; }
        public string RegionName { get; set; }
        public Nullable<byte> RegionID { get; set; }
        public Nullable<System.TimeSpan> StartTime { get; set; }
        public Nullable<System.TimeSpan> EndTime { get; set; }
        public Nullable<System.TimeSpan> TTime { get; set; }
        public Nullable<System.DateTime> DutyDate { get; set; }
        public string Remarks { get; set; }
        public Nullable<int> AssignedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string UserName { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public string WorkCardName { get; set; }
        public Nullable<short> JobCardID { get; set; }
        public string AssigedByName { get; set; }
        public int ID { get; set; }
    }
}
