//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViewLvConsumed
    {
        public string LeaveType { get; set; }
        public string DesignationName { get; set; }
        public string GradeName { get; set; }
        public string CompName { get; set; }
        public string JobTitle { get; set; }
        public string RegionName { get; set; }
        public string CityName { get; set; }
        public string LocName { get; set; }
        public string CrewName { get; set; }
        public string TypeName { get; set; }
        public string CatName { get; set; }
        public string ShiftName { get; set; }
        public string EmpNo { get; set; }
        public string EmpName { get; set; }
        public Nullable<int> DesigID { get; set; }
        public Nullable<short> JobID { get; set; }
        public Nullable<byte> Gender { get; set; }
        public string CardNo { get; set; }
        public Nullable<int> FpID { get; set; }
        public string PinCode { get; set; }
        public string FatherName { get; set; }
        public string NicNo { get; set; }
        public string BloodGroup { get; set; }
        public Nullable<System.DateTime> BirthDate { get; set; }
        public string MarStatus { get; set; }
        public Nullable<System.DateTime> JoinDate { get; set; }
        public Nullable<System.DateTime> ValidDate { get; set; }
        public Nullable<System.DateTime> IssueDate { get; set; }
        public Nullable<System.DateTime> ResignDate { get; set; }
        public string HomeAdd { get; set; }
        public Nullable<bool> Status { get; set; }
        public string PhoneNo { get; set; }
        public string SectionName { get; set; }
        public string DeptName { get; set; }
        public Nullable<short> CompanyID { get; set; }
        public Nullable<byte> TypeID { get; set; }
        public Nullable<short> CatID { get; set; }
        public Nullable<double> JanConsumed { get; set; }
        public Nullable<double> FebConsumed { get; set; }
        public Nullable<double> MarchConsumed { get; set; }
        public Nullable<double> AprConsumed { get; set; }
        public Nullable<double> MayConsumed { get; set; }
        public Nullable<double> JuneConsumed { get; set; }
        public Nullable<double> JulyConsumed { get; set; }
        public Nullable<double> AugustConsumed { get; set; }
        public Nullable<double> SepConsumed { get; set; }
        public Nullable<double> OctConsumed { get; set; }
        public Nullable<double> NovConsumed { get; set; }
        public Nullable<double> DecConsumed { get; set; }
        public Nullable<double> TotalForYear { get; set; }
        public Nullable<double> YearRemaining { get; set; }
        public Nullable<double> GrandTotal { get; set; }
        public Nullable<double> GrandTotalRemaining { get; set; }
        public string EmpLvType { get; set; }
        public string LvDesc { get; set; }
        public Nullable<byte> ShiftID { get; set; }
        public short DeptID { get; set; }
        public Nullable<short> GradeID { get; set; }
        public Nullable<short> CrewID { get; set; }
        public Nullable<short> LocID { get; set; }
        public Nullable<short> SecID { get; set; }
        public string DivisionName { get; set; }
        public short DivID { get; set; }
        public int EmpID { get; set; }
    }
}
