//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViewMonthlyDataPer
    {
        public string EmpMonth { get; set; }
        public string EmpNo { get; set; }
        public string EmpName { get; set; }
        public string D22 { get; set; }
        public string D21 { get; set; }
        public string D23 { get; set; }
        public string D24 { get; set; }
        public string D25 { get; set; }
        public string D27 { get; set; }
        public string D26 { get; set; }
        public string D28 { get; set; }
        public string D29 { get; set; }
        public string D30 { get; set; }
        public string D31 { get; set; }
        public string D1 { get; set; }
        public string D2 { get; set; }
        public string D3 { get; set; }
        public string D4 { get; set; }
        public string D5 { get; set; }
        public string D6 { get; set; }
        public string D7 { get; set; }
        public string D8 { get; set; }
        public string D10 { get; set; }
        public string D9 { get; set; }
        public string D11 { get; set; }
        public string D13 { get; set; }
        public string D14 { get; set; }
        public string D15 { get; set; }
        public string D16 { get; set; }
        public string D17 { get; set; }
        public string D19 { get; set; }
        public string D20 { get; set; }
        public string D18 { get; set; }
        public string D12 { get; set; }
        public Nullable<byte> TotalDays { get; set; }
        public Nullable<byte> WorkDays { get; set; }
        public Nullable<byte> PreDays { get; set; }
        public Nullable<byte> AbDays { get; set; }
        public Nullable<byte> RestDays { get; set; }
        public Nullable<byte> GZDays { get; set; }
        public Nullable<byte> LeaveDays { get; set; }
        public Nullable<byte> OfficialDutyDays { get; set; }
        public Nullable<short> TEarlyIn { get; set; }
        public Nullable<short> TEarlyOut { get; set; }
        public Nullable<short> TLateIn { get; set; }
        public Nullable<short> TLateOut { get; set; }
        public Nullable<short> TWorkTime { get; set; }
        public Nullable<short> TNOT { get; set; }
        public Nullable<short> TGZOT { get; set; }
        public Nullable<short> ExpectedWrkTime { get; set; }
        public Nullable<short> OT1 { get; set; }
        public Nullable<short> OT2 { get; set; }
        public Nullable<short> OT3 { get; set; }
        public Nullable<short> OT4 { get; set; }
        public Nullable<short> OT5 { get; set; }
        public Nullable<short> OT6 { get; set; }
        public Nullable<short> OT7 { get; set; }
        public Nullable<short> OT8 { get; set; }
        public Nullable<short> OT9 { get; set; }
        public Nullable<short> OT10 { get; set; }
        public Nullable<short> OT11 { get; set; }
        public Nullable<short> OT13 { get; set; }
        public Nullable<short> OT12 { get; set; }
        public Nullable<short> OT14 { get; set; }
        public Nullable<short> OT16 { get; set; }
        public Nullable<short> OT15 { get; set; }
        public Nullable<short> OT17 { get; set; }
        public Nullable<short> OT18 { get; set; }
        public Nullable<short> OT19 { get; set; }
        public Nullable<short> OT20 { get; set; }
        public Nullable<short> OT21 { get; set; }
        public Nullable<short> OT22 { get; set; }
        public Nullable<short> OT23 { get; set; }
        public Nullable<short> OT24 { get; set; }
        public Nullable<short> OT25 { get; set; }
        public Nullable<short> OT26 { get; set; }
        public Nullable<short> OT27 { get; set; }
        public Nullable<short> OT28 { get; set; }
        public Nullable<short> OT29 { get; set; }
        public Nullable<short> OT30 { get; set; }
        public Nullable<short> OT31 { get; set; }
        public string DesignationName { get; set; }
        public string GradeName { get; set; }
        public string CompName { get; set; }
        public string JobTitle { get; set; }
        public string CityName { get; set; }
        public string RegionName { get; set; }
        public string LocName { get; set; }
        public string CrewName { get; set; }
        public string TypeName { get; set; }
        public string CatName { get; set; }
        public string ShiftName { get; set; }
        public string DeptName { get; set; }
        public string SectionName { get; set; }
        public string DivisionName { get; set; }
        public Nullable<bool> Status { get; set; }
        public Nullable<int> EmpID { get; set; }
        public string CardNo { get; set; }
        public string Period { get; set; }
        public Nullable<byte> TypeID { get; set; }
        public Nullable<short> CompanyID { get; set; }
        public Nullable<short> CatID { get; set; }
        public Nullable<short> LocID { get; set; }
        public Nullable<short> CrewID { get; set; }
        public Nullable<short> GradeID { get; set; }
        public Nullable<short> DeptID { get; set; }
        public Nullable<byte> ShiftID { get; set; }
        public Nullable<short> DivID { get; set; }
        public Nullable<short> SecID { get; set; }
        public Nullable<int> DesigID { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
    }
}
