//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViewLvApplication
    {
        public int EmpID { get; set; }
        public System.DateTime LvDate { get; set; }
        public int LvID { get; set; }
        public System.DateTime FromDate { get; set; }
        public System.DateTime ToDate { get; set; }
        public float NoOfDays { get; set; }
        public Nullable<bool> IsHalf { get; set; }
        public Nullable<bool> FirstHalf { get; set; }
        public Nullable<bool> HalfAbsent { get; set; }
        public string LvReason { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public string LvAddress { get; set; }
        public string LvStatus { get; set; }
        public string DeptName { get; set; }
        public string SectionName { get; set; }
        public string DesignationName { get; set; }
        public string EmpNo { get; set; }
        public string EmpName { get; set; }
        public Nullable<byte> ShiftID { get; set; }
        public Nullable<int> DesigID { get; set; }
        public Nullable<short> LocID { get; set; }
        public Nullable<byte> TypeID { get; set; }
        public Nullable<short> SecID { get; set; }
        public string CardNo { get; set; }
        public Nullable<System.DateTime> JoinDate { get; set; }
        public Nullable<bool> Status { get; set; }
        public string TypeName { get; set; }
        public string LocName { get; set; }
        public string ShiftName { get; set; }
        public short DeptID { get; set; }
        public string LeaveTypeID { get; set; }
        public string FldName { get; set; }
        public string LvDesc { get; set; }
        public Nullable<bool> Deleted { get; set; }
    }
}
