//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViewBadli
    {
        public Nullable<int> BadliDesgID { get; set; }
        public string DesignationName { get; set; }
        public string DutyCode { get; set; }
        public Nullable<System.TimeSpan> DutyTime { get; set; }
        public Nullable<System.DateTime> TimeIn { get; set; }
        public Nullable<System.DateTime> TimeOut { get; set; }
        public Nullable<short> WorkMin { get; set; }
        public Nullable<short> LateIn { get; set; }
        public Nullable<short> LateOut { get; set; }
        public Nullable<short> EarlyIn { get; set; }
        public Nullable<short> EarlyOut { get; set; }
        public Nullable<short> OTMin { get; set; }
        public Nullable<short> GZOTMin { get; set; }
        public Nullable<short> BreakMin { get; set; }
        public Nullable<System.TimeSpan> SLMin { get; set; }
        public Nullable<bool> StatusP { get; set; }
        public Nullable<bool> StatusAB { get; set; }
        public int BadliID { get; set; }
        public Nullable<System.DateTime> AttDate { get; set; }
        public string EmpDateBadli { get; set; }
        public string DeptName { get; set; }
        public short DeptID { get; set; }
        public Nullable<short> CityID { get; set; }
        public int EmpID { get; set; }
        public Nullable<short> CrewID { get; set; }
        public Nullable<short> GradeID { get; set; }
        public Nullable<short> LocID { get; set; }
        public Nullable<byte> TypeID { get; set; }
        public Nullable<byte> ShiftID { get; set; }
        public Nullable<short> SecID { get; set; }
        public Nullable<short> CatID { get; set; }
        public Nullable<short> CompanyID { get; set; }
        public string DivisionName { get; set; }
        public string SectionName { get; set; }
        public string EmpName { get; set; }
        public string Expr2 { get; set; }
        public string ShiftName { get; set; }
        public string CatName { get; set; }
        public string TypeName { get; set; }
        public string CrewName { get; set; }
        public string LocName { get; set; }
        public string RegionName { get; set; }
        public string CityName { get; set; }
        public string CompName { get; set; }
        public string GradeName { get; set; }
        public string Expr3 { get; set; }
        public short DivID { get; set; }
        public string Remarks { get; set; }
    }
}
