//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViewLeaveQuota
    {
        public int EmpID { get; set; }
        public string DesignationName { get; set; }
        public string GradeName { get; set; }
        public string CompName { get; set; }
        public string JobTitle { get; set; }
        public string CityName { get; set; }
        public string RegionName { get; set; }
        public string LocName { get; set; }
        public string CrewName { get; set; }
        public string TypeName { get; set; }
        public string CatName { get; set; }
        public string ShiftName { get; set; }
        public string EmpNo { get; set; }
        public string EmpName { get; set; }
        public Nullable<byte> Gender { get; set; }
        public Nullable<bool> Status { get; set; }
        public string SectionName { get; set; }
        public string DeptName { get; set; }
        public string DivisionName { get; set; }
        public int Expr1 { get; set; }
        public double B { get; set; }
        public double C { get; set; }
        public Nullable<double> D { get; set; }
        public Nullable<double> E { get; set; }
        public Nullable<double> F { get; set; }
        public Nullable<double> G { get; set; }
        public Nullable<double> H { get; set; }
        public Nullable<double> I { get; set; }
        public Nullable<double> J { get; set; }
        public Nullable<double> K { get; set; }
        public Nullable<double> L { get; set; }
        public double A { get; set; }
        public Nullable<double> TA { get; set; }
        public Nullable<double> TB { get; set; }
        public Nullable<double> TC { get; set; }
        public Nullable<double> TD { get; set; }
        public Nullable<double> TE { get; set; }
        public Nullable<double> TF { get; set; }
        public Nullable<double> TG { get; set; }
        public Nullable<double> TH { get; set; }
        public Nullable<double> TI { get; set; }
        public Nullable<double> TJ { get; set; }
        public Nullable<double> TK { get; set; }
        public Nullable<double> TL { get; set; }
        public Nullable<short> CompanyID { get; set; }
        public Nullable<byte> TypeID { get; set; }
        public Nullable<short> CatID { get; set; }
        public Nullable<int> DesigID { get; set; }
        public Nullable<short> CrewID { get; set; }
        public short DivID { get; set; }
        public short DeptID { get; set; }
        public Nullable<short> GradeID { get; set; }
        public Nullable<short> LocID { get; set; }
        public Nullable<byte> ShiftID { get; set; }
        public Nullable<short> SecID { get; set; }
    }
}
