//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DailySummary
    {
        public string SummaryDateCriteria { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<short> TotalEmps { get; set; }
        public Nullable<short> PresentEmps { get; set; }
        public Nullable<short> AbsentEmps { get; set; }
        public Nullable<short> LvEmps { get; set; }
        public Nullable<short> ShortLvEmps { get; set; }
        public Nullable<short> HalfLvEmps { get; set; }
        public Nullable<short> LIEmps { get; set; }
        public Nullable<short> DayOffEmps { get; set; }
        public Nullable<short> LOEmps { get; set; }
        public Nullable<short> EIEmps { get; set; }
        public Nullable<short> EOEmps { get; set; }
        public Nullable<short> OTEmps { get; set; }
        public Nullable<short> OnTimeEmps { get; set; }
        public Nullable<int> LIMins { get; set; }
        public Nullable<int> LOMins { get; set; }
        public Nullable<int> EIMins { get; set; }
        public Nullable<int> EOMins { get; set; }
        public Nullable<int> OTMins { get; set; }
        public Nullable<int> ExpectedWorkMins { get; set; }
        public Nullable<int> ActualWorkMins { get; set; }
        public Nullable<int> LossWorkMins { get; set; }
        public Nullable<short> ALIMins { get; set; }
        public Nullable<short> ALOMins { get; set; }
        public Nullable<short> AEIMins { get; set; }
        public Nullable<short> AEOMins { get; set; }
        public Nullable<short> AOTMins { get; set; }
        public Nullable<short> AExpectedMins { get; set; }
        public Nullable<short> AActualMins { get; set; }
        public Nullable<short> ALossMins { get; set; }
        public string Criteria { get; set; }
        public Nullable<short> CriteriaValue { get; set; }
        public string CriteriaName { get; set; }
        public Nullable<System.TimeSpan> AverageTimeIn { get; set; }
        public Nullable<System.TimeSpan> AverageTimeOut { get; set; }
    }
}
