//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmpFace
    {
        public int EmpID { get; set; }
        public string Face1 { get; set; }
        public Nullable<int> Length { get; set; }
    
        public virtual Emp Emp { get; set; }
    }
}
