//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmpFp
    {
        public int EmpID { get; set; }
        public string Fp1 { get; set; }
        public string Fp2 { get; set; }
        public string Fp3 { get; set; }
        public string Fp4 { get; set; }
        public string Fp5 { get; set; }
        public string Fp6 { get; set; }
    
        public virtual Emp Emp { get; set; }
    }
}
