//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reason
    {
        public Reason()
        {
            this.Cards = new HashSet<Card>();
        }
    
        public byte ReasonID { get; set; }
        public string ReasonName { get; set; }
    
        public virtual ICollection<Card> Cards { get; set; }
    }
}
