//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Region
    {
        public Region()
        {
            this.Cities = new HashSet<City>();
        }
    
        public byte RegionID { get; set; }
        public string RegionName { get; set; }
    
        public virtual ICollection<City> Cities { get; set; }
    }
}
