//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RosterApp
    {
        public int RotaApplD { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public Nullable<System.DateTime> DateStarted { get; set; }
        public Nullable<System.DateTime> DateEnded { get; set; }
        public Nullable<int> UserID { get; set; }
        public string RosterCriteria { get; set; }
        public Nullable<int> CriteriaData { get; set; }
        public Nullable<bool> Status { get; set; }
        public Nullable<byte> RotaTypeID { get; set; }
        public Nullable<short> WorkMin { get; set; }
        public Nullable<System.TimeSpan> DutyTime { get; set; }
        public Nullable<byte> ShiftID { get; set; }
        public Nullable<short> CompanyID { get; set; }
    
        public virtual RosterType RosterType { get; set; }
        public virtual Shift Shift { get; set; }
    }
}
