//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViewCard
    {
        public int EmpID { get; set; }
        public string EmpNo { get; set; }
        public string EmpName { get; set; }
        public string CardTypeName { get; set; }
        public Nullable<bool> active { get; set; }
        public Nullable<bool> CardStatus { get; set; }
        public string Remarks { get; set; }
        public Nullable<System.DateTime> DateOfExpiry { get; set; }
        public Nullable<System.DateTime> DateOfIssue { get; set; }
        public string DesignationName { get; set; }
        public string DeptName { get; set; }
        public string NicNo { get; set; }
        public string FatherName { get; set; }
        public Nullable<System.DateTime> JoinDate { get; set; }
        public Nullable<System.DateTime> ValidDate { get; set; }
        public Nullable<System.DateTime> IssueDate { get; set; }
        public string PhoneNo { get; set; }
        public Nullable<bool> Status { get; set; }
        public string CellNo { get; set; }
        public string Email { get; set; }
        public string SectionName { get; set; }
        public string ReasonName { get; set; }
        public byte[] EmpPic { get; set; }
        public string CardNo { get; set; }
        public Nullable<short> CompanyID { get; set; }
        public Nullable<byte> TypeID { get; set; }
    }
}
