//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViewDetailAttData
    {
        public string EmpDate { get; set; }
        public Nullable<System.DateTime> AttDate { get; set; }
        public string Expr2 { get; set; }
        public string DutyCode { get; set; }
        public Nullable<System.TimeSpan> DutyTime { get; set; }
        public Nullable<System.DateTime> TimeIn { get; set; }
        public Nullable<System.DateTime> TimeOut { get; set; }
        public Nullable<short> WorkMin { get; set; }
        public Nullable<short> LateIn { get; set; }
        public Nullable<short> LateOut { get; set; }
        public Nullable<short> EarlyOut { get; set; }
        public Nullable<short> EarlyIn { get; set; }
        public Nullable<short> OTMin { get; set; }
        public Nullable<short> GZOTMin { get; set; }
        public Nullable<bool> StatusP { get; set; }
        public Nullable<bool> StatusAB { get; set; }
        public Nullable<bool> StatusLI { get; set; }
        public Nullable<bool> StatusEI { get; set; }
        public Nullable<bool> StatusLO { get; set; }
        public Nullable<bool> StatusEO { get; set; }
        public Nullable<bool> StatusOT { get; set; }
        public Nullable<bool> StatusGZOT { get; set; }
        public Nullable<bool> StatusGZ { get; set; }
        public Nullable<bool> StatusDO { get; set; }
        public Nullable<bool> StatusHD { get; set; }
        public Nullable<bool> StatusSL { get; set; }
        public Nullable<bool> StatusOD { get; set; }
        public Nullable<bool> StatusHL { get; set; }
        public Nullable<bool> StatusLeave { get; set; }
        public Nullable<bool> StatusMN { get; set; }
        public Nullable<short> ShifMin { get; set; }
        public string Expr3 { get; set; }
        public Nullable<System.DateTime> Tin0 { get; set; }
        public Nullable<System.DateTime> Tout0 { get; set; }
        public Nullable<System.DateTime> Tin1 { get; set; }
        public Nullable<System.DateTime> Tout1 { get; set; }
        public Nullable<System.DateTime> Tin2 { get; set; }
        public Nullable<System.DateTime> Tout2 { get; set; }
        public Nullable<System.DateTime> Tin3 { get; set; }
        public Nullable<System.DateTime> Tout3 { get; set; }
        public Nullable<System.DateTime> Tin4 { get; set; }
        public Nullable<System.DateTime> Tout4 { get; set; }
        public Nullable<System.DateTime> Tin5 { get; set; }
        public Nullable<System.DateTime> Tout5 { get; set; }
        public Nullable<System.DateTime> Tin6 { get; set; }
        public Nullable<System.DateTime> Tout6 { get; set; }
        public string DesignationName { get; set; }
        public string GradeName { get; set; }
        public string CompName { get; set; }
        public string JobTitle { get; set; }
        public string CityName { get; set; }
        public string RegionName { get; set; }
        public string LocName { get; set; }
        public string CrewName { get; set; }
        public string TypeName { get; set; }
        public string CatName { get; set; }
        public string ShiftName { get; set; }
        public string EmpNo { get; set; }
        public string EmpName { get; set; }
        public Nullable<short> JobID { get; set; }
        public Nullable<int> DesigID { get; set; }
        public Nullable<byte> Gender { get; set; }
        public string CardNo { get; set; }
        public Nullable<int> FpID { get; set; }
        public string PinCode { get; set; }
        public string FatherName { get; set; }
        public string NicNo { get; set; }
        public string BloodGroup { get; set; }
        public Nullable<System.DateTime> BirthDate { get; set; }
        public string MarStatus { get; set; }
        public Nullable<System.DateTime> JoinDate { get; set; }
        public Nullable<System.DateTime> ValidDate { get; set; }
        public Nullable<System.DateTime> IssueDate { get; set; }
        public Nullable<System.DateTime> ResignDate { get; set; }
        public string HomeAdd { get; set; }
        public bool ProcessAtt { get; set; }
        public Nullable<bool> Status { get; set; }
        public string PhoneNo { get; set; }
        public string Email { get; set; }
        public string Remarks { get; set; }
        public string CellNo { get; set; }
        public Nullable<bool> FlagFP { get; set; }
        public Nullable<bool> FlagFace { get; set; }
        public Nullable<bool> FlagCard { get; set; }
        public string SectionName { get; set; }
        public string DeptName { get; set; }
        public string DivisionName { get; set; }
        public Nullable<short> CompanyID { get; set; }
        public Nullable<short> CatID { get; set; }
        public Nullable<short> SecID { get; set; }
        public Nullable<byte> ShiftID { get; set; }
        public Nullable<byte> TypeID { get; set; }
        public Nullable<short> LocID { get; set; }
        public Nullable<short> GradeID { get; set; }
        public short DeptID { get; set; }
        public short DivID { get; set; }
        public Nullable<short> CrewID { get; set; }
        public Nullable<short> CityID { get; set; }
        public int EmpID { get; set; }
    }
}
