//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViewEmpType
    {
        public Nullable<short> CompanyID { get; set; }
        public string CompName { get; set; }
        public Nullable<short> CatID { get; set; }
        public string TypeName { get; set; }
        public byte TypeID { get; set; }
        public string CatName { get; set; }
    }
}
